Repository newsuk/times-components-native, pull requests merged in 2020-08, with the labels that each got.

#74 chore: Configuration for Semantic Pull Requests
  .github/semantic.yml
Labels: ready for review

#77 chore: Setup Navigation
  .eslintignore
  .github/CONTRIBUTING.md
  .gitignore
  .prettierignore
  README.md
  android/app/src/main/java/com/timescomponents/MainActivity.java
  android/app/src/main/java/com/timescomponents/MainApplication.java
  android/build.gradle
  app/index.ts
  app/metro.config.js
  app/navigation/ids.js
  app/navigation/index.js
  app/navigation/options.tsx
  app/storybook/index.js
  app/storybook/rn-addons.js
  app/utils/colors.ts
  app/utils/fonts.ts
  app/views/Edition.tsx
  app/views/More.tsx
  app/views/MyArticles.tsx
  app/views/PastSixDays.tsx
  assets/tabs/home.png
  assets/tabs/home@2x.png
  assets/tabs/home@3x.png
  assets/tabs/more.png
  assets/tabs/more@2x.png
  assets/tabs/more@3x.png
  assets/tabs/myarticles.png
  assets/tabs/myarticles@2x.png
  assets/tabs/myarticles@3x.png
  assets/tabs/p6d.png
  assets/tabs/p6d@2x.png
  assets/tabs/p6d@3x.png
  ios/Podfile.lock
  ios/TimesComponents.xcodeproj/project.pbxproj
  ios/TimesComponents/AppDelegate.h
  ios/TimesComponents/AppDelegate.m
  ios/TimesComponents/Info.plist
  lib/android/README.md
  lib/ios/README.md
  package.json
  storybook-native/.eslintignore
  storybook-native/.prettierignore
  storybook-native/CHANGELOG.md
  storybook-native/index.js
  storybook-native/storybook.js
  tsconfig.json
  yarn.lock
Labels: ready for review

#81 chore: Use gql-gen config file
  .gitignore
  codegen.yml
  package.json
  packages/fixture-generator/src/types.ts
  packages/schema/__tests__/__snapshots__/fetch-gql-schema.test.js.snap
  packages/schema/__tests__/fetch-gql-schema.test.js
  packages/schema/fetch-gql-schema.js
  packages/schema/fetchSchema.js
  packages/utils/README.md
  packages/utils/src/fragmentMatcher.js
  scripts/fetch-fonts.js
  yarn.lock
Labels: ready for review

#82 chore: Remove web storybook
  .depcheckrc
  .eslintrc.js
  .github/CONTRIBUTING.md
  .storybook/addons.js
  .storybook/config.js
  .storybook/manager-head.html
  .storybook/preview-head.html
  .storybook/vendor.webpack.config.js
  .storybook/webpack.config.js
  package.json
  yarn.lock
Labels: ready for review

#80 chore(NO-JIRA): Send release notes to Slack
  .depcheckrc
  package.json
  scripts/publish-notes.sh
  scripts/send-slack-message.js
  yarn.lock
Labels: ready for review

#61 feat: Variant tested inline single and double MPU (mainstandard only)
  packages/ad/__tests__/ad.shared.js
  packages/ad/__tests__/android/__snapshots__/ad.android.test.js.snap
  packages/ad/__tests__/ios/__snapshots__/ad.ios.test.js.snap
  packages/ad/src/ad-prop-types.js
  packages/ad/src/ad.js
  packages/ad/src/utils/ad-init.js
  packages/ad/src/utils/generate-config.js
  packages/ad/src/utils/sizes.js
  packages/article-in-depth/src/article-in-depth.js
  packages/article-in-depth/src/article-prop-types/article-prop-types.js
  packages/article-magazine-comment/src/article-magazine-comment.js
  packages/article-magazine-comment/src/article-prop-types/article-prop-types.js
  packages/article-magazine-standard/src/article-magazine-standard.js
  packages/article-magazine-standard/src/article-prop-types/article-prop-types.js
  packages/article-main-comment/src/article-main-comment.js
  packages/article-main-comment/src/article-prop-types/article-prop-types.js
  packages/article-main-standard/src/article-main-standard.js
  packages/article-main-standard/src/article-prop-types/article-prop-types.js
  packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
  packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
  packages/article-skeleton/__tests__/body-utils.native.js
  packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
  packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
  packages/article-skeleton/__tests__/shared.base.js
  packages/article-skeleton/src/article-body/article-body-paragraph.js
  packages/article-skeleton/src/article-body/inline-paragraph.js
  packages/article-skeleton/src/article-skeleton-prop-types.js
  packages/article-skeleton/src/article-skeleton.js
  packages/article-skeleton/src/body-utils.js
  packages/pages/src/article/article-base.js
  packages/pages/src/article/article-prop-types.js
  packages/variant-testing/README.md
  packages/variant-testing/__tests__/.eslintrc.json
  packages/variant-testing/__tests__/android/__snapshots__/variant-testing.test.js.snap
  packages/variant-testing/__tests__/android/variant-testing.test.js
  packages/variant-testing/__tests__/ios/__snapshots__/variant-testing.test.js.snap
  packages/variant-testing/__tests__/ios/variant-testing.test.js
  packages/variant-testing/__tests__/shared.base.js
  packages/variant-testing/index.ts
  packages/variant-testing/src/variant-testing.tsx
Labels: do not merge

#99 feat(TNLT-4283): Update error boundaries text for articles
  packages/pages/src/article/index.js
  packages/pages/src/with-error-boundaries.js
Labels: ready for review

#110 fix(TNLT-3636): fixes In Your Inbox puff size and removes styled-components
  .github/CONTRIBUTING.md
  babel.config.js
  package.json
  packages/article-skeleton/__tests__/android/__snapshots__/inline-newsletter-puff.test.js.snap
  packages/article-skeleton/__tests__/android/__snapshots__/newsletter-puff-link.test.js.snap
  packages/article-skeleton/__tests__/inline-newsletter-puff.base.js
  packages/article-skeleton/__tests__/ios/__snapshots__/inline-newsletter-puff.test.js.snap
  packages/article-skeleton/__tests__/ios/__snapshots__/newsletter-puff-link.test.js.snap
  packages/article-skeleton/__tests__/newsletter-puff-link.base.js
  packages/article-skeleton/src/article-body/inline-newsletter-puff.js
  packages/article-skeleton/src/article-body/newsletter-puff-link.js
  packages/article-skeleton/src/styles/inline-newsletter-puff.js
  packages/storybook/index.js
  packages/storybook/src/storybook.js
  packages/storybook/src/styles.js
  packages/utils/src/hover-icon.js
  yarn.lock
Labels: do not merge

#113 feat: front lead one
  package.json
  packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
  packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
  packages/edition-slices/__tests__/android/__snapshots__/tile-f-front.test.js.snap
  packages/edition-slices/__tests__/android/tile-f-front.test.js
  packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
  packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
  packages/edition-slices/__tests__/ios/__snapshots__/tile-f-front.test.js.snap
  packages/edition-slices/__tests__/ios/tile-f-front.test.js
  packages/edition-slices/__tests__/shared-tablet-slices.base.js
  packages/edition-slices/__tests__/tile-f-front/shared-tile-f-front.base.js
  packages/edition-slices/__tests__/tile-f-front/shared-tile-f-front.native.js
  packages/edition-slices/edition-front.showcase.js
  packages/edition-slices/src/edition-slices.js
  packages/edition-slices/src/slices/frontleadone/index.js
  packages/edition-slices/src/slices/index.js
  packages/edition-slices/src/tiles/index.js
  packages/edition-slices/src/tiles/shared/tile-image.js
  packages/edition-slices/src/tiles/tile-f-front/index.js
  packages/edition-slices/src/tiles/tile-f-front/styles/index.js
  packages/fixture-generator/index.ts
  packages/fixture-generator/src/mock-slice.ts
  packages/fixture-generator/src/types.ts
  packages/front-page/front-tile-summary.tsx
  packages/provider-queries/src/section_fragment.graphql
  packages/slice-layout/__tests__/android/__snapshots__/front-l1-with-style.android.test.js.snap
  packages/slice-layout/__tests__/android/__snapshots__/front-l1.android.test.js.snap
  packages/slice-layout/__tests__/android/front-l1-with-style.android.test.js
  packages/slice-layout/__tests__/android/front-l1.android.test.js
  packages/slice-layout/__tests__/front-l1-with-style.native.js
  packages/slice-layout/__tests__/front-l1.base.js
  packages/slice-layout/__tests__/front-l1.native.js
  packages/slice-layout/__tests__/ios/__snapshots__/front-l1-with-style.ios.test.js.snap
  packages/slice-layout/__tests__/ios/__snapshots__/front-l1.ios.test.js.snap
  packages/slice-layout/__tests__/ios/front-l1-with-style.ios.test.js
  packages/slice-layout/__tests__/ios/front-l1.ios.test.js
  packages/slice-layout/index.js
  packages/slice-layout/src/slice-layout.js
  packages/slice-layout/src/templates/frontleadone/index.js
  packages/slice-layout/src/templates/frontleadone/styles.android.js
  packages/slice-layout/src/templates/frontleadone/styles.js
Labels: work in progress
